targets:
  $default:
    builders:
      freezed:
        options:
          # Creates a `copyWith` function even for classes with @freezed
          copy_with: true
          # Creates a `toJson` function for freezed classes
          to_json: true
          # Creates a `fromJson` factory for freezed classes
          from_json: true
      riverpod_generator:
        options:
          # Generate Riverpod code
          generate_riverpod: true
      json_serializable:
        options:
          # Performance optimization: skip unnecessary checks in generated code
          checked: false
          # Only generate what's needed
          create_to_json: true
          create_factory: true

# Global build runner options for better performance
global_options:
  # Enable caching to speed up subsequent builds
  "*":
    enable_caching: true
    # Increase concurrency for faster builds (adjust based on CPU cores)
    # Set to number of CPU cores for optimal performance (8-16 for modern CPUs)
    max_concurrent_builders: 12
    # Skip dev dependencies for faster builds
    skip_dev_dependencies: false
    # Use symlinks when possible (faster on some systems)
    use_symlinks: true
