targets:
  $default:
    builders:
      freezed:
        options:
          # Creates a `copyWith` function even for classes with @freezed
          copy_with: true
          # Creates a `toJson` function for freezed classes
          to_json: true
          # Creates a `fromJson` factory for freezed classes
          from_json: true
      riverpod_generator:
        options:
          # Generate Riverpod code
          generate_riverpod: true

# Global build runner options for better performance
global_options:
  # Enable caching to speed up subsequent builds
  "*":
    enable_caching: true
    # Increase concurrency for faster builds (adjust based on CPU cores)
    max_concurrent_builders: 8
